//
//  RosterColormap.swift
//  Hot Wheels v Human
//
//  Makes the Skin / Shirt / Pants swatches real on the twelve Kenney roster
//  characters.
//
//  Those characters aren't blank meshes like the old Quaternius rig — their
//  whole appearance is painted into one shared 512×512 colormap, which is why
//  DriverPainter's stripe palette skips them (`bakedAppearance`) and why the
//  swatches used to change a saved value and nothing on screen.
//
//  The colormap is an 8×8 grid of 64 px cells, and one material is a vertical
//  PAIR of cells (light row over dark row — its shading ramp). So a garment is
//  a 64×128 patch, and dressing a character differently is repainting the two
//  or three patches they wear. Patch indices come from the mesh UVs offline
//  (tools/extract_roster_palette.py), never from matching colours at runtime:
//  two characters share shades all over this sheet, and colour matching would
//  bleed one garment into another.
//

import Foundation

nonisolated enum RosterColormap {
    /// Bundled copy of the pack's shared texture.
    static let resourceName = "roster-colormap"

    /// Grid geometry of the sheet. Asserted against the real image in tests
    /// rather than trusted, since everything below indexes with it.
    static let grid = 8
    static let rowsPerPatch = 2

    /// A patch address: `row` counts row-PAIRS (0…3), `col` counts cells (0…7).
    struct Patch: Hashable, Sendable {
        let row: Int
        let col: Int
        init(_ row: Int, _ col: Int) { self.row = row; self.col = col }
    }

    /// Which patch a character wears for each recolourable part. `shoes` is
    /// recorded but never repainted — there's no shoe swatch in the editor,
    /// and it's here so the next person doesn't have to re-derive it.
    struct Patches: Sendable {
        let skin: Patch
        let shirt: Patch
        let pants: Patch
        let shoes: Patch
        /// The eyes' own cell — nil on characters where the eye texels ARE the
        /// hair or a dark garment (Kenney maps a whole cell to one flat texel,
        /// so those can't be recoloured apart). Non-nil ones honour the Eyes
        /// swatch; nil ones keep the sheet's dark default.
        let eyes: Patch?

        init(skin: [Int], shirt: [Int], pants: [Int], shoes: [Int],
             eyes: [Int]? = nil) {
            self.skin = Patch(skin[0], skin[1])
            self.shirt = Patch(shirt[0], shirt[1])
            self.pants = Patch(pants[0], pants[1])
            self.shoes = Patch(shoes[0], shoes[1])
            self.eyes = eyes.map { Patch($0[0], $0[1]) }
        }
    }

    // Generated by tools/extract_roster_palette.py — do not hand-edit.
    // Trailing colours are the patch each role resolved to, checked against
    // Graphics/3DModels/Source/kenney_mini-characters/Previews/*.png.
    static let patches: [String: Patches] = [
        "character-female-a": .init(skin: [3, 6], shirt: [2, 5], pants: [2, 5], shoes: [3, 7]),   // skin #8B5641 shirt #585ABF pants #585ABF shoes #E0A57E
        "character-female-b": .init(skin: [3, 7], shirt: [2, 2], pants: [2, 7], shoes: [3, 4], eyes: [3, 0]),   // skin #ECB690 shirt #FFD061 pants #8F63D8 shoes #D1D1E2 eyes #3B3B41
        "character-female-c": .init(skin: [3, 5], shirt: [2, 5], pants: [3, 1], shoes: [3, 7], eyes: [3, 0]),   // skin #BC6A49 shirt #5D6CC7 pants #7C8199 shoes #E0A57E eyes #3B3B41
        "character-female-d": .init(skin: [3, 7], shirt: [3, 1], pants: [3, 1], shoes: [3, 0], eyes: [3, 0]),   // skin #D28F68 shirt #696F86 pants #696F86 shoes #3B3B41 eyes #3B3B41
        "character-female-e": .init(skin: [3, 7], shirt: [3, 4], pants: [3, 0], shoes: [3, 3]),   // skin #ECB690 shirt #C9C9DD pants #353539 shoes #878DA9
        "character-female-f": .init(skin: [3, 7], shirt: [2, 2], pants: [2, 5], shoes: [2, 7], eyes: [3, 0]),   // skin #ECB690 shirt #FF952F pants #5E70C9 shoes #855BD2 eyes #3B3B41
        "character-male-a": .init(skin: [3, 6], shirt: [2, 1], pants: [2, 5], shoes: [2, 2]),   // skin #A95E41 shirt #20896B pants #5D6CC7 shoes #FFBA4E
        "character-male-b": .init(skin: [3, 7], shirt: [2, 4], pants: [2, 5], shoes: [3, 5], eyes: [3, 0]),   // skin #E9B28C shirt #EB6246 pants #6282D1 shoes #DA845D eyes #3B3B41
        "character-male-c": .init(skin: [3, 7], shirt: [2, 5], pants: [3, 0], shoes: [3, 0]),   // skin #ECB690 shirt #6282D1 pants #3B3B41 shoes #3B3B41
        "character-male-d": .init(skin: [3, 7], shirt: [3, 0], pants: [3, 0], shoes: [3, 0]),   // skin #ECB690 shirt #3B3B41 pants #3B3B41 shoes #3B3B41
        "character-male-e": .init(skin: [3, 7], shirt: [3, 4], pants: [3, 4], shoes: [3, 1], eyes: [3, 0]),   // skin #ECB690 shirt #C7C7DB pants #C7C7DB shoes #61677E eyes #3B3B41
        "character-male-f": .init(skin: [3, 5], shirt: [2, 1], pants: [3, 7], shoes: [3, 1]),   // skin #E38B62 shirt #319A74 pants #D99A72 shoes #61677E
    ]

    /// The eyes always sample this one cell — see the table: every separable
    /// character reads `eyes: [3, 0]`.
    static let eyeCell = Patch(3, 0)

    /// True when the eyes can't be recoloured (`eyes` is nil) AND that cell is
    /// a garment we repaint, so the eyes would take the shirt/pants colour.
    /// Nothing can paint them apart — the eye texels ARE that garment's texels
    /// in Kenney's flat-cell art — so the fix is to cover them: these
    /// characters wear glasses whether the profile asked for them or not (the
    /// boy default, male-d, is one of them). Characters whose eye cell is
    /// unpainted hair keep plain dark eyes and are false here.
    static func eyesTakeGarmentColor(for profile: DriverProfile) -> Bool {
        guard let p = patches[key(for: profile)] else { return false }
        return p.eyes == nil && (p.shirt == eyeCell || p.pants == eyeCell)
    }

    /// The table key for a profile — the roster person, without the pose or
    /// bald-cut suffix `DriverProfile.modelName` adds.
    static func key(for profile: DriverProfile) -> String {
        let body = profile.bodyType ?? .man
        var variant = profile.characterVariant ?? body.defaultVariant
        if !body.variants.contains(variant) { variant = body.defaultVariant }
        return "character-\(body.isFemale ? "female" : "male")-\(variant)"
    }

    /// Patch → colour, in paint order. Some characters wear a one-piece
    /// outfit whose top and bottom are the same patch (`male-d`, `male-e`,
    /// `female-a`, `female-d`); shirt is applied last so on those the Shirt
    /// swatch is the one that wins, since it's the one kids reach for.
    static func repaints(for profile: DriverProfile) -> [(patch: Patch, hex: String)] {
        guard let patches = patches[key(for: profile)] else { return [] }
        var out: [(patch: Patch, hex: String)] = [
            (patches.skin, profile.skinToneHex),
            // Same darkening the stripe palette gives the Quaternius rig, so
            // a shirt and pants picked from one swatch read as an outfit on
            // both bodies rather than as pajamas on one of them.
            (patches.pants,
             DriverPalette.darkened(profile.pantsColorHex ?? DriverPalette.defaultPantsColor,
                                    by: DriverPalette.pantsDarkening)),
            (patches.shirt, profile.suitColorHex),
        ]
        // Eyes LAST, so on a character whose eye cell is also its shoe cell
        // (female-d) the eyes win — shoes aren't a swatch. Only the six
        // characters with a separable eye cell get here; the rest keep the
        // sheet's dark eyes. ponytail: the other six can't be split — eyes and
        // that garment are one flat texel in Kenney's art; upgrade needs
        // editing the model UVs, which are pristine upstream assets.
        if let eyes = patches.eyes {
            out.append((eyes, profile.eyeColorHex ?? DriverPalette.defaultEyeColor))
        }
        return out
    }

    /// Repaint `patch` in an RGBA byte buffer, keeping the ramp's shading:
    /// each texel gets `hex` scaled by how bright it was relative to the
    /// brightest texel in that patch. Flat-filling instead would throw away
    /// the light/dark rows that give these models their shape.
    ///
    /// Silently does nothing for a patch that's entirely black — that's an
    /// unused cell of the sheet, and dividing by its zero peak would paint a
    /// square of pure colour into the middle of the texture.
    static func repaint(_ pixels: inout [UInt8], width: Int, height: Int,
                        patch: Patch, hex: String) {
        guard let rgb = DriverPalette.rgb(hex: hex) else { return }
        let cell = width / grid
        let x0 = patch.col * cell
        let y0 = patch.row * rowsPerPatch * (height / grid)
        let x1 = min(width, x0 + cell)
        let y1 = min(height, y0 + rowsPerPatch * (height / grid))
        guard x0 < x1, y0 < y1 else { return }

        func luminance(_ i: Int) -> Double {
            0.299 * Double(pixels[i]) + 0.587 * Double(pixels[i + 1])
                + 0.114 * Double(pixels[i + 2])
        }

        var peak = 0.0
        for y in y0..<y1 {
            for x in x0..<x1 { peak = max(peak, luminance((y * width + x) * 4)) }
        }
        guard peak > 0 else { return }

        for y in y0..<y1 {
            for x in x0..<x1 {
                let i = (y * width + x) * 4
                let shade = luminance(i) / peak
                pixels[i] = UInt8(clamping: Int((Double(rgb.x) * 255 * shade).rounded()))
                pixels[i + 1] = UInt8(clamping: Int((Double(rgb.y) * 255 * shade).rounded()))
                pixels[i + 2] = UInt8(clamping: Int((Double(rgb.z) * 255 * shade).rounded()))
            }
        }
    }
}
